# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hi": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://wiessall.github.io/nbdev-tut/"

git_url = "https://github.com/wiessall/nbdev-tut/tree/master/"

def custom_doc_links(name): return None
